set nocompatible

" General Settings
syntax on

set t_Co=256
set showmatch
set relativenumber
set showmatch
set expandtab
set autoindent
set fileformat=unix
set backspace=2

set splitbelow
set splitright

nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

set tags=./.tags,.tags,./tags,tags

" The Silver Searcher
if executable('ag')
  " Use ag over grep
  set grepprg=ag\ --nogroup\ --nocolor

  " Use ag in CtrlP for listing files. Lightning fast and respects .gitignore
  let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'

  " ag is fast enough that CtrlP doesn't need to cache
  let g:ctrlp_use_caching = 0
endif

" Deoplete autocompletion
"let g:deoplete#enable_at_startup = 0

" Airline plugin
set laststatus=2
let g:airline_solarized_bg='dark'
let g:airline_powerline_fonts = 1

" Scala settings
au BufNewFile, Bufread *.sc*
    \ set tabstop=2
    \ set softtabstop=2
    \ set shiftwidth=2
    \ set textwidth=99

" vim-scala
let g:scala_sort_across_groups=1
let g:scala_scaladoc_indent = 1

" ensime-vim
autocmd BufWritePost *.scala silent :EnTypeCheck
nnoremap <localleader>t: EnType<CR>

" Python settings
au BufNewFile, BufRead *.py
    \ set tabstop=4
    \ set softtabstop=4
    \ set shiftwidth=4
    \ set textwidth=79

au BufNewFile, BufRead *.c
    \ set tabstop=4
    \ set softtabstop=4
    \ set shiftwidth=4
    \ set textwidth=79

""" NERDTree Settings
map <C-n> :NERDTreeToggle<CR>

" All nerdtree to modify files
set modifiable
let g:NERDTreeWinWize = 60

" Start nerdtree by default
autocmd vimenter * NERDTree

" Open NERDTree automatically when vim starts and no files specified
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif

" Open NERDTree when opening a directory
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) && !exists("s:std_in") | exe 'NERDTree' argv()[0] | wincmd p | ene | endif

" Close NERDTree if it is the only window remaining
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

" CtrlP Settings
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'
let g:ctrlp_by_filename = 1 " search by file name not path

" Ale Settings
"let g:airline#extensions#ale#enabled = 1
"let b:ale_fixers = ['autopep8', 'yapf']

" python-mode settings
let g:pymode = 1
let g:pymode_doc = 0
set completeopt=menu
